dfm <- read.table("train.csv",sep=",",header = T)
ndf <- subset(dfm,dfm$humidity < 40)
dim(dfm)
attributes(dfm)
class(dfm)
typeof(dfm)
names(dfm)
nrow(dfm)
ncol(dfm)
range(dfm$humidity)
hist(dfm$windspeed)
plot(dfm$humidity)
plot(dfm$windspeed)
plot(lm(dfm$count ~ dfm$temp))
plot(dfm$temp,dfm$count)
barplot(dfm$season)
stem(dfm$count)
library(lattice)
densityplot(dfm$temp)
densityplot(log(dfm$temp))
hist(dfm$temp, breaks=10, main="Temprature distribution",
     xlab="temp", col="gray")
